name: reusable_workflow_test

on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
      module_major_version:
        required: false
        type: string
      module_minor_version:
        required: false
        type: string

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "Hello, ${{ env.module_name }}"
