name: reusable_workflow_test

on:
  workflow_call:
    inputs:
      MODULE_NAME:
        required: true
        type: string
      MAJOR_PACKAGE_VERSION:
        required: false
        type: string
      MINOR_PACKAGE_VERSION:
        required: false
        type: string
      BUILD_TYPE:
        required: false
        type: string

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: check_out_repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/devops-continous_integration_github.git
          token: ${{secrets.access_token_github}}
          path: devops-continous_integration_github
          ref: main
      # https://github.com/marketplace/actions/checkout
      - name: check_out_repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ github.event.repository.name }}.git
          token: ${{secrets.access_token_github}}
          path: ${{ github.event.repository.name }}
          ref: main
      - name: find_latest_package_version
        shell: pwsh
        run: ./devops-continous_integration_github/powershell/scripts/version.ps1 -ModuleName ${{ inputs.MODULE_NAME }} -MajorPackageVersion ${{ inputs.MAJOR_PACKAGE_VERSION }} -MinorPackageVersion ${{ inputs.MINOR_PACKAGE_VERSION }}
      # https://github.com/marketplace/actions/upload-a-build-artifact
      - name: upload_artifact_package_version
        uses: actions/upload-artifact@v3
        with:
          name: package_version
          path: package_version.env