name: reusable_workflow_test

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "Hello, World"
