name: reusable_powershell-workflow

on:
  workflow_call:
    inputs:
      MODULE_NAME:
        required: true
        type: string
      MAJOR_PACKAGE_VERSION:
        required: false
        type: string
      MINOR_PACKAGE_VERSION:
        required: false
        type: string
      BUILD_TYPE:
        required: false
        type: string

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: check_out_repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/devops-continous_integration_github.git
          token: ${{secrets.access_token_github}}
          path: devops-continous_integration_github
          ref: main
      # https://github.com/marketplace/actions/checkout
      - name: check_out_repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ github.event.repository.name }}.git
          token: ${{secrets.access_token_github}}
          path: ${{ github.event.repository.name }}
          ref: main
      - name: find_latest_package_version
        shell: pwsh
        run: ./devops-continous_integration_github/powershell/scripts/version.ps1 -ModuleName ${{ inputs.MODULE_NAME }} -MajorPackageVersion ${{ inputs.MAJOR_PACKAGE_VERSION }} -MinorPackageVersion ${{ inputs.MINOR_PACKAGE_VERSION }}
      # https://github.com/marketplace/actions/upload-a-build-artifact
      - name: upload_artifact_package_version
        uses: actions/upload-artifact@v3
        with:
          name: package_version
          path: package_version.env

  package:
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/setup-dotnet
      - name: setup_dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          dotnet-quality: 'ga'
      # https://github.com/marketplace/actions/checkout
      - name: check_out_repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/devops-continous_integration_github.git
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          path: devops-continous_integration_github
          ref: main
      # https://github.com/marketplace/actions/checkout
      - name: check_out_repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ github.event.repository.name }}.git
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          path: ${{ github.event.repository.name }}
          ref: main
      # https://github.com/marketplace/actions/download-a-build-artifact
      - name: download_artifact_package_version
        uses: actions/download-artifact@v3
        with:
          name: package_version
      - name: set_environment_variable_package_version
        run: |
          echo "PACKAGE_VERSION=$(cat package_version.env)" >> $GITHUB_ENV
          echo $GITHUB_ENV
      - name: replace_version_in_files
        shell: pwsh
        run: |
          ./devops-continous_integration_github/powershell/scripts/pack.ps1 -ModuleName ${{ inputs.MODULE_NAME }} -ModuleDirectory ${{ github.workspace }}\${{ github.event.repository.name }} -PackageVersion ${{ env.PACKAGE_VERSION }} -BuildType ${{ inputs.BUILD_TYPE }}
      # https://github.com/marketplace/actions/upload-a-build-artifact
      - name: upload_artifact_nuget_file
        uses: actions/upload-artifact@v3
        with:
          name: nuget_file
          path: ${{ github.workspace }}/${{ github.event.repository.name }}/bin/${{ inputs.BUILD_TYPE }}/${{ inputs.MODULE_NAME }}.${{ env.PACKAGE_VERSION }}.nupkg

  publish:
    needs: [version, package]
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/setup-dotnet
      - name: setup_dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          dotnet-quality: 'ga'
      # https://github.com/marketplace/actions/download-a-build-artifact
      - name: download_artifact_package_version
        uses: actions/download-artifact@v3
        with:
          name: nuget_file
      # https://github.com/marketplace/actions/download-a-build-artifact
      - name: download_artifact_package_version
        uses: actions/download-artifact@v3
        with:
          name: package_version
      - name: set_environment_variable_package_version
        run: |
          echo "PACKAGE_VERSION=$(cat package_version.env)" >> $GITHUB_ENV
          echo $GITHUB_ENV
      - name: replace_version_in_files
        shell: pwsh
        run: |
          dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name "github" "https://nuget.pkg.github.com/OWNER/index.json"
          dotnet nuget push ".\${{ inputs.BUILD_TYPE }}\${{ inputs.MODULE_NAME }}.${{ env.PACKAGE_VERSION }}.nupkg" --api-key ${{ secrets.ACCESS_TOKEN_GITHUB }} --source "github"