name: reusable_workflow_test

on:
  workflow_call:
    inputs:
      MODULE_NAME:
        required: true
        type: string
      MODULE_MAJOR_VERSION:
        required: false
        type: string
      MODULE_MINOR_VERSION:
        required: false
        type: string
      BUILD_TYPE:
        required: false
        type: string

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "Hello, ${{ inputs.MODULE_NAME }}"

      - name: find_latest_package_version
        shell: pwsh
        run: ./devops-continous_integration/powershell/scripts/version.ps1 -ModuleName ${{ env.MODULE_NAME }} -MajorPackageVersion ${{ env.MAJOR_PACKAGE_VERSION }} -MinorPackageVersion ${{ env.MINOR_PACKAGE_VERSION }}
      # https://github.com/marketplace/actions/upload-a-build-artifact